### ISSUE TITLE
Support Typescript 5

### ISSUE THREAD

**Issue by JakeAi** [NativeScript/angular#115]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - NativeScript-Angular: 16
 - Angular: 16
 
**Describe the bug**
Using Angular 16 which uses Typescript 5 and updated TSLib renders custom activities unusable and does not allow the app to start. Refer to this chat

https://discord.com/channels/603595811204366337/606457628729671691/1108803693844901968

```
System.err: An uncaught Exception occurred on "main" thread.
  System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
  System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "com.companymfg.activity" not found.
  System.err: File: (file: src\webpack:\inventory\webpack\bootstrap:27:0)
  System.err:
  System.err: StackTrace:
  System.err: (/data/data/com.companymfg.inventory/files/internal/ts_helpers.js:154:26)
  System.err:   at __esDecorate(file: src\webpack:\inventory\node_modules\tslib\tslib.es6.js:77:0)
  System.err:   at (file:///data/data/com.companymfg.inventory/files/app/bundle.js:741:9)
  System.err:   at (file:///data/data/com.companymfg.inventory/files/app/bundle.js:744:7)
  System.err:   at ./src/activity.android.ts(file:///data/data/com.companymfg.inventory/files/app/bundle.js:746:2)
  System.err:   at __webpack_require__(file: src\webpack:\inventory\webpack\bootstrap:24:0)
  System.err:   at __webpack_exec__(file:///data/data/com.companymfg.inventory/files/app/bundle.js:71277:39)
  System.err:   at (file:///data/data/com.companymfg.inventory/files/app/bundle.js:71278:224)
  System.err:   at __webpack_require__.X(file: src\webpack:\inventory\webpack\runtime\startup entrypoint:6:0)
  System.err:   at (file:///data/data/com.companymfg.inventory/files/app/bundle.js:71278:47)
  System.err:   at (file:///data/data/com.companymfg.inventory/files/app/bundle.js:71283:3)
  System.err:   at require(:1:266)

```

**To Reproduce**

Update Typescript to 5, TSLib 2.5, Angular 16. Use custom activity as stated in Nativescript Docs

**Expected behavior**
App to run normally

**Sample project**

**Additional context**
